# Generated by Django 4.1.4 on 2022-12-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('nama_bunga', models.CharField(max_length=100, verbose_name='Nama Bunga')),
                ('harga', models.FloatField(verbose_name='Harga (Rp)')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('detail_nama_bunga', models.CharField(max_length=100, verbose_name='Detail Nama Bunga')),
                ('detail_harga', models.FloatField(verbose_name='Harga (Rp)')),
                ('sku', models.CharField(max_length=50, verbose_name='Detail SKU')),
                ('kategori', models.CharField(choices=[('Pacar Air (Balsam)', 'Benih Pacar Air (Balsam)'), ('Mr Fothergills', ' Benih Mr Fothergills'), ('Larkspur & Delphinium', 'Benih Larkspur & Delphinium'), ('Buddleja (Butterfly Bush)', 'Benih Buddleja (Butterfly Bush)'), ('Nasturtium', 'Benih Nasturtium'), ('Bayam', 'Benih Bayam'), ('Jagung', 'Benih Jagung'), ('Cosmos', 'Benih Cosmos'), ('Bit Merah', 'Benih Bit Merah'), ('Semangka', 'Benih Semangka'), ('Bintang Asia', 'Benih Bintang Asia'), ('Labu', 'Benih Labu'), ('Berkebun', 'Perlengkapan Berkebun'), ('Hidroponik', 'Tanaman Hidroponik'), ('Herbisida', 'Tanaman Herbisida'), ('Bunga Matahari (Sunflower)', 'Bebih Bunga Matahari (Sunflower)')], max_length=50, verbose_name='Kategori')),
            ],
        ),
    ]
