# Generated by Django 4.1.4 on 2022-12-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunga',
            name='detail_harga',
            field=models.CharField(max_length=100, verbose_name='Harga (Rp)'),
        ),
        migrations.AlterField(
            model_name='bunga',
            name='harga',
            field=models.CharField(max_length=100, verbose_name='Harga (Rp)'),
        ),
    ]
